(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var time=0,prevtime=0,distance=0,prevscroll=null,pool=[],timeout=null,flush=function(){time=0,prevtime=0,distance=0,prevscroll=0,pool=[]};exports.default=function(e){var t=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{timeStamp:0},l=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},o=0;if(!t.timeStamp||0===t.timeStamp)return 0;time=t.timeStamp-prevtime,distance=Math.abs(e-prevscroll||0),prevscroll=e,prevtime=t.timeStamp,pool.push(distance/(time*(1/(l.interval||100)))),pool.length>(l.pool||10)&&pool.shift(),(timeout=setTimeout(flush,l.reset||50))&&clearTimeout(timeout);for(var i=0;i<pool.length;i++)return o=pool[i]+o,{velocity:o/(i+1),flush:flush};return{velocity:0,flush:flush}};
},{}],2:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}var _index=require("../package/index.js"),_index2=_interopRequireDefault(_index);document.addEventListener("DOMContentLoaded",function(e){var n=document.getElementById("view");(0,_index2.default)(function(){n.innerHTML="up"},function(){n.innerHTML="down"},{speed:100})});
},{"../package/index.js":3}],3:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}function _objectWithoutProperties(e,r){var t={};for(var u in e)0<=r.indexOf(u)||Object.prototype.hasOwnProperty.call(e,u)&&(t[u]=e[u]);return t}Object.defineProperty(exports,"__esModule",{value:!0});var _srraf=require("srraf"),_srraf2=_interopRequireDefault(_srraf),_svel2=require("svel"),_svel3=_interopRequireDefault(_svel2);exports.default=function(e,r){var t=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},u=null;return Object.create(function(t){var o=t.speed,n=void 0===o?50:o,i=_objectWithoutProperties(t,["speed"]);return _srraf2.default?_srraf2.default.scroll.use(function(t,o){var s=t.curr,a=t.prev,l=(0,_svel3.default)(s,o,i),f=l.velocity,p=l.flush,_=f>(void 0===n?50:n);s>=a&&"down"!==u&&_?(u="down",r&&r(),p()):s<=a&&"up"!==u&&_&&(u="up",e&&e(),p())}).update():{}}(t),{position:{get:function(){return u}}})};
},{"srraf":4,"svel":1}],4:[function(require,module,exports){
"use strict";function _classCallCheck(e,r){if(!(e instanceof r))throw new TypeError("Cannot call a class as a function")}var _createClass=function(){function e(e,r){for(var t,n=0;n<r.length;n++)t=r[n],t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(e,t.key,t)}return function(r,t,n){return t&&e(r.prototype,t),n&&e(r,n),r}}();Object.defineProperty(exports,"__esModule",{value:!0});var scrollInstance=null,resizeInstance=null,Listener=function(){function e(r){_classCallCheck(this,e),this.type=r,this.pool=0,this.queue=[],this.curr=this.position(),this.prev=this.position(),this.ticking=!1,window.addEventListener(r,this.requestFrame.bind(this))}return _createClass(e,[{key:"position",value:function(){return"scroll"===this.type?window.scrollY||window.pageYOffset:window.innerWidth}},{key:"requestFrame",value:function(e){this.e=e,this.curr=this.position(),this.ticking||(window.requestAnimationFrame(this.run.bind(this)),this.ticking=!0)}},{key:"run",value:function(){var e=this;this.queue.forEach(function(r){return r[1]({curr:e.curr,prev:e.prev},e.e)}),this.prev=this.curr,this.ticking=!1}},{key:"use",value:function(e){var r=this,t=r.pool++;return r.queue.push([t,e]),{destroy:function(){return r.queue.forEach(function(e,n){e[0]===t&&r.queue.splice(n,1)}),this},update:function(){return e({curr:r.curr,prev:r.prev},r.e),this}}}},{key:"update",value:function(){this.run()}}]),e}();exports.default="undefined"==typeof window?null:{get scroll(){return scrollInstance||(scrollInstance=new Listener("scroll")),scrollInstance},get resize(){return resizeInstance||(resizeInstance=new Listener("resize")),resizeInstance},use:function(e){var r=this.scroll,t=r.curr,n=r.prev,i=this.resize,s=i.curr,u=i.prev,c={currY:t,prevY:n,currX:s,prevX:u},o=this.scroll.use(function(r,t){var n=r.curr,i=r.prev;c.currY=n,c.prevY=i,e(c,t)}),a=this.resize.use(function(r,t){var n=r.curr,i=r.prev;c.currX=n,c.prevX=i,e(c,t)});return{destroy:function(){return o.destroy(),a.destroy(),this},update:function(){return o.update(),a.update(),this}}}};
},{}]},{},[2])


//# sourceMappingURL=demo.js.map