(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}var _index=require("../package/index.js"),_index2=_interopRequireDefault(_index);document.addEventListener("DOMContentLoaded",function(e){var n=document.getElementById("view"),t=(0,_index2.default)({speed:100});t.on("up",function(){return n.innerHTML="up"}),t.on("down",function(){return n.innerHTML="down"})});
},{"../package/index.js":2}],2:[function(require,module,exports){
"use strict";function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}function _objectWithoutProperties(e,r){var t={};for(var o in e)0<=r.indexOf(o)||Object.prototype.hasOwnProperty.call(e,o)&&(t[o]=e[o]);return t}var _extends=Object.assign||function(e){for(var r,t=1;t<arguments.length;t++)for(var o in r=arguments[t])Object.prototype.hasOwnProperty.call(r,o)&&(e[o]=r[o]);return e},_srraf=require("srraf"),_srraf2=_interopRequireDefault(_srraf),_svel2=require("svel"),_svel3=_interopRequireDefault(_svel2),_loop=require("loop.js"),_loop2=_interopRequireDefault(_loop);Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=function(){var e=0<arguments.length&&void 0!==arguments[0]?arguments[0]:{},r=null,t=(0,_loop2.default)();return Object.create(_extends({},function(e){var o=e.speed,u=void 0===o?50:o,n=_objectWithoutProperties(e,["speed"]);return _srraf2.default?_srraf2.default.scroll.use(function(e,o){var i=e.curr,l=e.prev,a=(0,_svel3.default)(i,o,n),s=a.velocity,f=a.flush,p=s>(void 0===u?50:u),_=function(e){r=e,t.emit(e),f&&f()};i>=l&&"down"!==r&&p?_("down"):i<=l&&"up"!==r&&p?_("up"):"static"!==r&&!p&&_("static")}).update():{}}(e),t),{position:{get:function(){return r}}})};
},{"loop.js":3,"srraf":4,"svel":5}],3:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var _extends=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var n=arguments[t];for(var r in n)Object.prototype.hasOwnProperty.call(n,r)&&(e[r]=n[r])}return e};exports.default=function(){var e=arguments.length>0&&void 0!==arguments[0]?arguments[0]:{},t={},n=function(e){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null;n&&(t[e]=t[e]||{queue:[]},t[e].queue.push(n))};return _extends({},e,{emit:function(e){var n=arguments.length>1&&void 0!==arguments[1]?arguments[1]:null,r=!!t[e]&&t[e].queue;r&&r.forEach(function(e){return e(n)})},on:n})};
},{}],4:[function(require,module,exports){
"use strict";function _classCallCheck(e,r){if(!(e instanceof r))throw new TypeError("Cannot call a class as a function")}var _createClass=function(){function e(e,r){for(var t,n=0;n<r.length;n++)t=r[n],t.enumerable=t.enumerable||!1,t.configurable=!0,"value"in t&&(t.writable=!0),Object.defineProperty(e,t.key,t)}return function(r,t,n){return t&&e(r.prototype,t),n&&e(r,n),r}}();Object.defineProperty(exports,"__esModule",{value:!0});var scrollInstance=null,resizeInstance=null,Listener=function(){function e(r){_classCallCheck(this,e),this.type=r,this.pool=0,this.queue=[],this.curr=this.position(),this.prev=this.position(),this.ticking=!1,window.addEventListener(r,this.requestFrame.bind(this))}return _createClass(e,[{key:"position",value:function(){return"scroll"===this.type?window.scrollY||window.pageYOffset:window.innerWidth}},{key:"requestFrame",value:function(e){this.e=e,this.curr=this.position(),this.ticking||(window.requestAnimationFrame(this.run.bind(this)),this.ticking=!0)}},{key:"run",value:function(){var e=this;this.queue.forEach(function(r){return r[1]({curr:e.curr,prev:e.prev},e.e)}),this.prev=this.curr,this.ticking=!1}},{key:"use",value:function(e){var r=this,t=r.pool++;return r.queue.push([t,e]),{destroy:function(){return r.queue.forEach(function(e,n){e[0]===t&&r.queue.splice(n,1)}),this},update:function(){return e({curr:r.curr,prev:r.prev},r.e),this}}}},{key:"update",value:function(){this.run()}}]),e}();exports.default="undefined"==typeof window?null:{get scroll(){return scrollInstance||(scrollInstance=new Listener("scroll")),scrollInstance},get resize(){return resizeInstance||(resizeInstance=new Listener("resize")),resizeInstance},use:function(e){var r=this.scroll,t=r.curr,n=r.prev,i=this.resize,s=i.curr,u=i.prev,c={currY:t,prevY:n,currX:s,prevX:u},o=this.scroll.use(function(r,t){var n=r.curr,i=r.prev;c.currY=n,c.prevY=i,e(c,t)}),a=this.resize.use(function(r,t){var n=r.curr,i=r.prev;c.currX=n,c.prevX=i,e(c,t)});return{destroy:function(){return o.destroy(),a.destroy(),this},update:function(){return o.update(),a.update(),this}}}};
},{}],5:[function(require,module,exports){
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var time=0,prevtime=0,distance=0,prevscroll=null,pool=[],timeout=null,flush=function(){time=0,prevtime=0,distance=0,prevscroll=0,pool=[]};exports.default=function(e){var t=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{timeStamp:0},l=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},o=0;if(!t.timeStamp||0===t.timeStamp)return 0;time=t.timeStamp-prevtime,distance=Math.abs(e-prevscroll||0),prevscroll=e,prevtime=t.timeStamp,pool.push(distance/(time*(1/(l.interval||100)))),pool.length>(l.pool||10)&&pool.shift(),(timeout=setTimeout(flush,l.reset||50))&&clearTimeout(timeout);for(var i=0;i<pool.length;i++)return o=pool[i]+o,{velocity:o/(i+1),flush:flush};return{velocity:0,flush:flush}};
},{}]},{},[1])


//# sourceMappingURL=demo.js.map